[
  {
    "id": 0,
    "constraints": [
      {
        "lower_bound": [
          {
            "y": -1.334371,
            "x": 13.943108
          }
        ]
      },
      {
        "upper_bound": [
          {
            "y": -3.136289,
            "x": 18.612106
          }
        ]
      }
    ]
  },
  {
    "id": 1,
    "constraints": [
      {
        "lower_bound": [
          {
            "y": -1.008725,
            "x": 21.483109
          }
        ]
      },
      {
        "upper_bound": [
          {
            "y": -3.29981,
            "x": 25.409983
          }
        ]
      }
    ]
  }
]
